### ISSUE TITLE
Semantic versioning has been completely broken

### ISSUE THREAD

**Issue by LFalch** [LFalch/delta-l#4]
Due to my giant misunderstanding of semver, it hasn't been used properly in any way in this project.

I don't see any way to fix this.

**Comment by mtib** [comment]
Does the strict semantic-versioning "codex" even apply to this project? As you are not dealing with any public API or a server / client structure, and your file en- and decryption is backwards compatible, your way to version it seems fine to me.

Also nice work hours :+1:

**Comment by LFalch** [comment]
No, I guess it doesn't matter too much, but I shouldn't have come to version 1 before lately.

**Comment by mtib** [comment]
The email feature is nice, but you have to delete the "old" content. :D

**Comment by LFalch** [comment]
Right, now I know that for the future :D
